# Generated by Django 5.2.7 on 2025-10-01 19:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0019_auto_20210618_1728"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam_model",
            name="end_time",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 10, 2, 0, 37, 20, 398466)
            ),
        ),
        migrations.AlterField(
            model_name="exam_model",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="exam_model",
            name="start_time",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 10, 2, 0, 37, 20, 398448)
            ),
        ),
        migrations.AlterField(
            model_name="question_paper",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
