# Generated by Django 5.2.7 on 2025-10-01 20:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0020_alter_exam_model_end_time_alter_exam_model_id_and_more"),
    ]

    operations = []
